[package]
name = "dltui-viewer-core"
description = "Contains the core elements for dltui-viewer"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
directories = "6.0.0"
serde = { version = "1", features = ["derive"] }
toml = "1.1.2"
regex = "1.13.1"
chrono = { version = "0.4.45", features = ["serde"] }

[lints]
workspace = true
