[package]
name = "dltui-viewer-dlt"
description = "Handles DLT files"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
chrono = "0.4.45"
dlt_parse = { version = "0.10.1", features = ["serde"] }
